export interface DoseRange {
  min: number;
  max: number;
}

export interface ToxinBrandData {
  [muscle: string]: DoseRange;
}

export interface ToxinData {
  Dysport: ToxinBrandData;
  Botox: ToxinBrandData;
  Xeomin: ToxinBrandData;
}

export const dosisData: ToxinData = {
  Dysport: {
    // Facial and Migraine Muscles (standardized nomenclature)
    "Cervical Paraspinals": { min: 50, max: 100 },
    "Corrugator": { min: 25, max: 50 },
    "Frontalis": { min: 50, max: 100 },
    "Occipitalis": { min: 75, max: 150 },
    "Orbicularis oculi": { min: 30, max: 72 },
    "Procerus": { min: 12, max: 25 },
    "Temporalis": { min: 100, max: 200 },
    "Trapezius": { min: 75, max: 150 },
    
    // Spasticity Muscles
    "Abductor hallucis": { min: 40, max: 80 },
    "Adductor longus": { min: 125, max: 250 },
    "Adductor magnus": { min: 250, max: 500 },
    "Adductor pollicis longus": { min: 60, max: 100 },
    "Biceps brachii": { min: 200, max: 300 },
    "Biceps femoris": { min: 250, max: 375 },
    "Brachialis": { min: 125, max: 200 },
    "Brachioradialis": { min: 125, max: 180 },
    "Coracobrachialis": { min: 75, max: 125 },
    "Cuadrado lumbar": { min: 250, max: 300 },
    "Deltoides": { min: 125, max: 225 },
    "Dorsal ancho": { min: 150, max: 240 },
    "Extensor carpi radialis brevis": { min: 50, max: 90 },
    "Extensor carpi radialis longus": { min: 75, max: 120 },
    "Extensor carpi ulnaris": { min: 75, max: 120 },
    "Extensor digiti minimi": { min: 75, max: 120 },
    "Extensor digitorum communis": { min: 75, max: 120 },
    "Extensor digitorum longus": { min: 125, max: 225 },
    "Extensor hallucis longus": { min: 125, max: 180 },
    "Extensor indicis": { min: 50, max: 90 },
    "Extensor pollicis brevis": { min: 50, max: 75 },
    "Extensor pollicis longus": { min: 50, max: 90 },
    "Flexor carpi radialis": { min: 75, max: 120 },
    "Flexor carpi ulnaris": { min: 75, max: 120 },
    "Flexor digitorum brevis": { min: 25, max: 60 },
    "Flexor digitorum longus": { min: 100, max: 180 },
    "Flexor digitorum profundus": { min: 75, max: 120 },
    "Flexor digitorum superficialis": { min: 75, max: 90 },
    "Flexor hallucis brevis": { min: 25, max: 60 },
    "Flexor hallucis longus": { min: 100, max: 180 },
    "Flexor pollicis longus": { min: 50, max: 90 },
    "Gastrocnemio (cabeza lateral)": { min: 125, max: 300 },
    "Gastrocnemio (cabeza medial)": { min: 125, max: 300 },
    "Glúteo medio": { min: 150, max: 225 },
    "Gracilis": { min: 200, max: 300 },
    "Ilíaco": { min: 125, max: 300 },
    "Infraespinoso": { min: 125, max: 180 },
    "Pectineus": { min: 125, max: 250 },
    "Pectoral mayor": { min: 200, max: 300 },
    "Pectoralis minor": { min: 100, max: 120 },
    "Peroneus brevis": { min: 75, max: 120 },
    "Peroneus longus": { min: 125, max: 240 },
    "Peroneus tertius": { min: 75, max: 113 },
    "Popliteus": { min: 63, max: 90 },
    "Pronator quadratus": { min: 50, max: 90 },
    "Pronator teres": { min: 75, max: 120 },
    "Psoas mayor": { min: 300, max: 500 },
    "Rectus femoris (cuádriceps anterior)": { min: 250, max: 375 },
    "Redondo mayor": { min: 75, max: 150 },
    "Redondo menor": { min: 75, max: 150 },
    "Romboides": { min: 125, max: 180 },
    "Semimembranosus": { min: 250, max: 375 },
    "Semitendinosus": { min: 250, max: 375 },
    "Serrato anterior": { min: 150, max: 210 },
    "Sóleo": { min: 200, max: 300 },
    "Subscapularis": { min: 125, max: 240 },
    "Superficial flexor muscles": { min: 75, max: 120 },
    "Supinador": { min: 75, max: 120 },
    "Supraespinoso": { min: 125, max: 150 },
    "Tibialis anterior": { min: 200, max: 300 },
    "Tibialis posterior": { min: 125, max: 240 },
    "Trapecio": { min: 125, max: 225 },
    "Triceps brachii": { min: 200, max: 300 },
    "Vastus lateralis, intermedius y medialis": { min: 250, max: 375 }
  },
  Botox: {
    // Facial and Migraine Muscles (standardized nomenclature)
    "Cervical Paraspinals": { min: 20, max: 40 },
    "Corrugator": { min: 10, max: 20 },
    "Frontalis": { min: 20, max: 40 },
    "Occipitalis": { min: 30, max: 60 },
    "Orbicularis oculi": { min: 12, max: 24 },
    "Procerus": { min: 5, max: 10 },
    "Temporalis": { min: 40, max: 80 },
    "Trapezius": { min: 30, max: 60 },
    
    // Spasticity Muscles
    "Abductor hallucis": { min: 10, max: 20 },
    "Adductor longus": { min: 50, max: 100 },
    "Adductor magnus": { min: 100, max: 200 },
    "Adductor pollicis longus": { min: 20, max: 40 },
    "Biceps brachii": { min: 75, max: 100 },
    "Biceps femoris": { min: 100, max: 150 },
    "Brachialis": { min: 50, max: 75 },
    "Brachioradialis": { min: 50, max: 60 },
    "Coracobrachialis": { min: 30, max: 50 },
    "Cuadrado lumbar": { min: 100, max: 120 },
    "Deltoides": { min: 50, max: 75 },
    "Dorsal ancho": { min: 60, max: 80 },
    "Extensor carpi radialis brevis": { min: 20, max: 30 },
    "Extensor carpi radialis longus": { min: 30, max: 40 },
    "Extensor carpi ulnaris": { min: 30, max: 40 },
    "Extensor digiti minimi": { min: 30, max: 40 },
    "Extensor digitorum communis": { min: 30, max: 40 },
    "Extensor digitorum longus": { min: 50, max: 75 },
    "Extensor hallucis longus": { min: 50, max: 60 },
    "Extensor indicis": { min: 20, max: 30 },
    "Extensor pollicis brevis": { min: 20, max: 25 },
    "Extensor pollicis longus": { min: 20, max: 30 },
    "Flexor carpi radialis": { min: 30, max: 40 },
    "Flexor carpi ulnaris": { min: 30, max: 40 },
    "Flexor digitorum brevis": { min: 10, max: 20 },
    "Flexor digitorum longus": { min: 40, max: 60 },
    "Flexor digitorum profundus": { min: 30, max: 40 },
    "Flexor digitorum superficialis": { min: 25, max: 30 },
    "Flexor hallucis brevis": { min: 10, max: 20 },
    "Flexor hallucis longus": { min: 40, max: 60 },
    "Flexor pollicis longus": { min: 20, max: 30 },
    "Gastrocnemio (cabeza lateral)": { min: 50, max: 100 },
    "Gastrocnemio (cabeza medial)": { min: 50, max: 100 },
    "Glúteo medio": { min: 60, max: 75 },
    "Gracilis": { min: 80, max: 120 },
    "Ilíaco": { min: 50, max: 120 },
    "Infraespinoso": { min: 50, max: 60 },
    "Pectineus": { min: 50, max: 100 },
    "Pectoral mayor": { min: 75, max: 100 },
    "Pectoralis minor": { min: 40, max: 40 },
    "Peroneus brevis": { min: 30, max: 40 },
    "Peroneus longus": { min: 50, max: 80 },
    "Peroneus tertius": { min: 30, max: 38 },
    "Popliteus": { min: 25, max: 30 },
    "Pronator quadratus": { min: 20, max: 30 },
    "Pronator teres": { min: 30, max: 40 },
    "Psoas mayor": { min: 120, max: 200 },
    "Rectus femoris (cuádriceps anterior)": { min: 100, max: 150 },
    "Redondo mayor": { min: 30, max: 50 },
    "Redondo menor": { min: 30, max: 50 },
    "Romboides": { min: 50, max: 60 },
    "Semimembranosus": { min: 100, max: 150 },
    "Semitendinosus": { min: 100, max: 150 },
    "Serrato anterior": { min: 60, max: 70 },
    "Sóleo": { min: 75, max: 100 },
    "Subscapularis": { min: 50, max: 80 },
    "Superficial flexor muscles": { min: 30, max: 40 },
    "Supinador": { min: 30, max: 40 },
    "Supraespinoso": { min: 50, max: 60 },
    "Tibialis anterior": { min: 75, max: 120 },
    "Tibialis posterior": { min: 50, max: 80 },
    "Trapecio": { min: 50, max: 75 },
    "Triceps brachii": { min: 75, max: 100 },
    "Vastus lateralis, intermedius y medialis": { min: 100, max: 150 }
  },
  Xeomin: {
    // Facial and Migraine Muscles (standardized nomenclature)
    "Cervical Paraspinals": { min: 20, max: 40 },
    "Corrugator": { min: 10, max: 20 },
    "Frontalis": { min: 20, max: 40 },
    "Occipitalis": { min: 30, max: 60 },
    "Orbicularis oculi": { min: 12, max: 24 },
    "Procerus": { min: 5, max: 10 },
    "Temporalis": { min: 40, max: 80 },
    "Trapezius": { min: 30, max: 60 },
    
    // Spasticity Muscles
    "Abductor hallucis": { min: 10, max: 20 },
    "Adductor longus": { min: 50, max: 100 },
    "Adductor magnus": { min: 100, max: 200 },
    "Adductor pollicis longus": { min: 20, max: 40 },
    "Biceps brachii": { min: 75, max: 100 },
    "Biceps femoris": { min: 100, max: 150 },
    "Brachialis": { min: 50, max: 75 },
    "Brachioradialis": { min: 50, max: 60 },
    "Coracobrachialis": { min: 30, max: 50 },
    "Cuadrado lumbar": { min: 100, max: 120 },
    "Deltoides": { min: 50, max: 75 },
    "Dorsal ancho": { min: 60, max: 80 },
    "Extensor carpi radialis brevis": { min: 20, max: 30 },
    "Extensor carpi radialis longus": { min: 30, max: 40 },
    "Extensor carpi ulnaris": { min: 30, max: 40 },
    "Extensor digiti minimi": { min: 30, max: 40 },
    "Extensor digitorum communis": { min: 30, max: 40 },
    "Extensor digitorum longus": { min: 50, max: 80 },
    "Extensor hallucis longus": { min: 50, max: 60 },
    "Extensor indicis": { min: 20, max: 30 },
    "Extensor pollicis brevis": { min: 20, max: 25 },
    "Extensor pollicis longus": { min: 20, max: 30 },
    "Flexor carpi radialis": { min: 30, max: 40 },
    "Flexor carpi ulnaris": { min: 30, max: 40 },
    "Flexor digitorum brevis": { min: 10, max: 20 },
    "Flexor digitorum longus": { min: 40, max: 60 },
    "Flexor digitorum profundus": { min: 30, max: 40 },
    "Flexor digitorum superficialis": { min: 25, max: 30 },
    "Flexor hallucis brevis": { min: 10, max: 20 },
    "Flexor hallucis longus": { min: 40, max: 60 },
    "Flexor pollicis longus": { min: 20, max: 30 },
    "Gastrocnemio (cabeza lateral)": { min: 50, max: 100 },
    "Gastrocnemio (cabeza medial)": { min: 50, max: 100 },
    "Glúteo medio": { min: 60, max: 75 },
    "Gracilis": { min: 80, max: 120 },
    "Ilíaco": { min: 50, max: 120 },
    "Infraespinoso": { min: 50, max: 60 },
    "Pectineus": { min: 50, max: 100 },
    "Pectoral mayor": { min: 75, max: 100 },
    "Pectoralis minor": { min: 40, max: 40 },
    "Peroneus brevis": { min: 30, max: 40 },
    "Peroneus longus": { min: 50, max: 80 },
    "Peroneus tertius": { min: 30, max: 40 },
    "Popliteus": { min: 25, max: 30 },
    "Pronator quadratus": { min: 20, max: 30 },
    "Pronator teres": { min: 30, max: 40 },
    "Psoas mayor": { min: 120, max: 200 },
    "Rectus femoris (cuádriceps anterior)": { min: 100, max: 150 },
    "Redondo mayor": { min: 30, max: 50 },
    "Redondo menor": { min: 30, max: 50 },
    "Romboides": { min: 50, max: 60 },
    "Semimembranosus": { min: 100, max: 150 },
    "Semitendinosus": { min: 100, max: 150 },
    "Serrato anterior": { min: 60, max: 70 },
    "Sóleo": { min: 75, max: 100 },
    "Subscapularis": { min: 50, max: 80 },
    "Superficial flexor muscles": { min: 30, max: 40 },
    "Supinador": { min: 30, max: 40 },
    "Supraespinoso": { min: 50, max: 60 },
    "Tibialis anterior": { min: 75, max: 120 },
    "Tibialis posterior": { min: 50, max: 80 },
    "Trapecio": { min: 50, max: 75 },
    "Triceps brachii": { min: 75, max: 100 },
    "Vastus lateralis, intermedius y medialis": { min: 100, max: 150 }
  }
};

export const puntosMotoresData: Record<string, string> = {
  "Abductor hallucis": "Se localiza en la región medial plantar del pie, justo distal al tubérculo del calcáneo. Para ubicarlo, palpa con el paciente en decúbito supino o sentado y solicita que realice una ligera flexión plantar y abducción del primer dedo; el punto de mínima resistencia a la estimulación eléctrica se encuentra aproximadamente en el punto medio entre el tubérculo calcáneo medial y la base de la primera falange proximal del hallux.",
  "Adductor longus": "Se ubica en la cara medial del muslo. Con el paciente en decúbito supino, cadera en ligera abducción y rotación externa, palpa a aproximadamente 3 cm inferior a la sínfisis púbica y 2–3 cm medial a la línea media del muslo. La contracción se confirma solicitando aducción activa del muslo contra resistencia; el punto motor suele hallarse a nivel del tercio proximal del músculo, donde el nervio obturador ingresa al vientre muscular.",
  "Adductor magnus": "Con el paciente en decúbito supino y la pierna ligeramente abducida, localiza la tuberosidad isquiática. El punto motor se encuentra unos 4–5 cm distal e inferior a esa tuberosidad, en la región medial del muslo, desde donde se observa una contracción con mínima estimulación al solicitar aducción de cadera contra resistencia.",
  "Adductor pollicis longus": "Nota: en la práctica clínica suele confundirse con 'adductor pollicis' (músculo de la mano). El verdadero 'adductor pollicis' (cabeza transversa y oblicua) se localiza en la parte carnosa de la eminencia tenar, entre la base del primer metacarpiano y la cabeza del segundo metacarpiano. Para encontrar el punto motor, coloca el pulgar en ligera oposición contra el índice; la mínima estimulación para obtener aducción del pulgar corresponde al punto motor, aproximadamente en el centro de la eminencia tenar profundizando ligeramente.",
  "Biceps brachii": "Se localiza en la mitad del brazo, sobre la línea que une el acromion con el pliegue del codo. Con el paciente sentado o en decúbito supino, palpa a aproximadamente 6–8 cm distal al acromion, en la cara anterior del brazo, unos 2–3 cm medial al surco bicipital. La contracción se confirma solicitando flexión de codo con supinación contra resistencia; el punto motor está donde se genere mayor contracción con la menor corriente.",
  "Biceps femoris": "Con el paciente en decúbito prono y la rodilla en ligera flexión (20–30°), localiza la tuberosidad isquiática y desciende unos 6–8 cm distal a lo largo del borde lateral del muslo. El punto motor del bíceps femoral (cabeza larga) se halla en la cara posterior-lateral del muslo, aproximadamente al nivel del tercio medio; la contracción se confirma solicitando flexión de rodilla contra resistencia.",
  "Brachialis": "Con el codo en ligera flexión (30°) y el antebrazo en pronación, palpa justo medial (profundo) al bíceps braquial, a nivel del tercio medio del brazo. El punto motor se sitúa aproximadamente 5–6 cm distal al acromion sobre la cara anterior del húmero, ligeramente medial al surco bicipital. La contracción se confirma solicitando flexión de codo con el antebrazo en pronación.",
  "Brachioradialis": "Con el codo en ligera flexión (90°) y antebrazo en posición neutra, palpa el músculo sobre la región anterolateral del antebrazo. El punto motor se halla a aproximadamente 5–7 cm distal al epicóndilo lateral, justo lateral al borde radial; la contracción se observa al solicitar flexión de codo contra resistencia.",
  "Coracobrachialis": "El paciente en decúbito supino con la cadera y rodilla en posición cómoda. Para localizarlo, palpa en la cara anteromedial del brazo, unos 6–8 cm distal al acromion y ligeramente medial al surco bicipital. Solicita flexión y aducción de cadera para confirmar contracción; el punto motor se halla donde el nervio musculocutáneo penetra el vientre muscular, aproximadamente a nivel del tercio proximal del brazo.",
  "Cuadrado lumbar": "Con el paciente en decúbito lateral sobre el lado contralateral, flexiona ligeramente la rodilla para relajar la región lumbar. El punto motor se localiza en la región lumbar posterior, entre la cresta ilíaca y el ángulo inferior de la décima costilla, aproximadamente a 3–4 cm lateral a la apófisis espinosa de la cuarta vértebra lumbar (L4). La contracción se confirma solicitando elevación lateral de la pelvis contra resistencia.",
  "Deltoides": "Con el paciente sentado o de pie, brazo en aducción pasiva. El punto motor para el deltoides se encuentra en el tercio medio del músculo, justo por debajo del acromion, sobre el punto más ancho del hombro (aprox. 2 cm distal al borde inferior del acromion). Solicita abducción del hombro contra resistencia para confirmar contracción durante la estimulación.",
  "Dorsal ancho": "Con el paciente sentado o de pie, y brazo en aducción y leve rotación interna, palpa en la región posterolateral del tórax, aproximadamente a nivel de la novena costilla, a unos 6–8 cm lateral a la línea media posterior (línea que une las apófisis espinosas). El punto motor se confirma al solicitar aducción y extensión de hombro contra resistencia; la estimulación mínima se logra aquí.",
  "Extensor carpi radialis brevis": "Paciente sentado con antebrazo apoyado en una mesa, muñeca en posición neutra. Palpa la cara dorsal-radial del antebrazo, a unos 5–6 cm distal al epicóndilo lateral, en la zona muscular próxima a la línea tendinosa del compartimento posterior. Solicita extensión y abducción de muñeca contra resistencia para confirmar contracción; el punto motor está donde se observe la contracción con el menor voltaje.",
  "Extensor carpi radialis longus": "Paciente sentado con antebrazo en pronación sobre la mesa. Palpa sobre la región dorsal-anterolateral del antebrazo, aproximadamente 4–5 cm distal al epicóndilo lateral, justo por delante del ECR brevis. Solicita extensión de muñeca con ligera abducción contra resistencia; el punto motor es ahí.",
  "Extensor carpi ulnaris": "Con el antebrazo en pronación y muñeca relajada, palpa en la cara dorsal-ulnar del antebrazo, a aproximadamente 6–8 cm distal al epicóndilo lateral, a la altura del borde medial del compartimento posterior. Solicita extensión y aducción de muñeca contra resistencia; el punto motor se localizará donde la contracción sea más evidente con mínima corriente.",
  "Extensor digiti minimi": "Con el antebrazo apoyado en la mesa y muñeca en ligera flexión, palpa en el compartimento posterior, cerca de la inserción del extensor de dedo meñique. Se encuentra aproximadamente 6–7 cm distal al epicóndilo lateral, sobre la línea que lleva al dedo meñique. Solicita extensión del quinto dedo contra resistencia; el punto motor es donde aparezca con menor estimulación.",
  "Extensor digitorum communis": "Paciente sentado con antebrazo en pronación, apóyalo en la mesa. Palpa el dorso del antebrazo, a nivel del punto medio entre el epicóndilo lateral y la muñeca, en la línea central del compartimento posterior. Solicita extensión de los dedos índice a meñique contra resistencia; el punto motor se ubica donde la contracción sea más fuerte con menor corriente.",
  "Extensor digitorum longus": "Con el paciente en decúbito supino y tobillo colgando fuera de la camilla (flexión plantar neutra), palpa la región anterolateral de la pierna, aproximadamente 8–10 cm proximal al maléolo lateral, justo lateral al peroné. Solicita dorsiflexión y extensión de dedos de los pies contra resistencia; el punto motor se encuentra donde la contracción sea máxima con mínima estimulación.",
  "Extensor hallucis longus": "Con el tobillo en ligera eversión y flexión plantar neutra, palpa entre el músculo tibial anterior y el músculo extensor digitorum longus, a unos 6–8 cm proximal al maléolo medial. Solicita dorsiflexión del dedo gordo contra resistencia; el punto motor se hallará donde se observe claramente la contracción con menor corriente.",
  "Extensor indicis": "Paciente en decúbito supino o sentado con antebrazo en pronación. Palpa en la cara dorsal del antebrazo distal, a nivel de 5–6 cm proximal a la muñeca, en la región entre el EDL y el EDM, en línea con el segundo metacarpiano. Solicita extensión del índice contra resistencia; el punto motor es donde se genere la contracción con el umbral más bajo.",
  "Extensor pollicis brevis": "Con el antebrazo en posición neutra o ligera pronación, palpa en el compartimento lateral dorsal del antebrazo distal, aproximadamente 4–5 cm proximal a la muñeca y lateral al ECRL. Solicita extensión y abducción del pulgar proximalmente contra resistencia; el punto motor se halla donde la contracción sea más evidente con menor corriente.",
  "Extensor pollicis longus": "Con el antebrazo ligeramente pronado y muñeca en posición neutra, localiza el compartimento dorsal distal, a 5–6 cm proximal a la muñeca, en la zona medial al EPL. Solicita extensión del pulgar distalmente contra resistencia; el punto motor se encuentra donde la contracción sea más potente al aplicar la menor estimulación.",
  "Flexor carpi radialis": "Paciente sentado con antebrazo apoyado y supinado. Palpa en la cara volar-anterior del antebrazo, aproximadamente 7–8 cm distal al epicóndilo medial, en el compartimento anterior superficial. Solicita flexión y abducción radial de la muñeca contra resistencia; el punto motor se halla donde la contracción se logre con mínimo voltaje.",
  "Flexor carpi ulnaris": "Con el antebrazo en ligera supinación y muñeca relajada, palpa en la cara anterior-ulnar del antebrazo, a unos 8 cm distal al epicóndilo medial, a nivel del compartimento anterior superficial. Para confirmar, solicita flexión y aducción ulnar de la muñeca contra resistencia; el punto motor se encontrará donde la contracción sea óptima con baja corriente.",
  "Flexor digitorum brevis": "Con el paciente en decúbito supino y rodilla flexionada, coloca el pie en posición neutra. Palpa en la región plantar media del pie, justo debajo de los metatarsos centrales (metatarsos 2–4). Solicita plantar flexión de los dedos menores contra resistencia; el punto motor se localiza donde la contracción se vea más marcada con la estimulación más baja.",
  "Flexor digitorum longus": "Con el paciente en decúbito supino y tobillo en posición neutra, palpa la cara posterior-medial de la pierna, aproximadamente 10–12 cm proximal al maléolo medial, justo posterior a la tibia. Solicita flexión de los dedos del pie contra resistencia; el punto motor se halla donde aparezca la contracción con menor voltaje.",
  "Flexor digitorum profundus": "Paciente sentado con antebrazo en supinación. Palpa la cara volar del antebrazo distal, a 7–8 cm proximal a la muñeca, justo medial al arco tendinoso del pronador cuadrado. Solicita flexión de las falanges distales de los dedos índice a anular contra resistencia; el punto motor se ubica donde se observe la contracción con el umbral mínimo.",
  "Flexor digitorum superficialis": "Con el antebrazo en supinación y el codo ligeramente flexionado, palpa la cara volar del antebrazo medio, a unos 7 cm distal al epicóndilo medial, en el músculo que forma un vientre más ancho. Solicita flexión de las falanges medias de los dedos (índice a anular) contra resistencia; el punto motor se encontrará donde la contracción se logre con la menor corriente.",
  "Flexor hallucis brevis": "Con el pie en posición neutra y rodilla flexionada, palpa en la región plantar del antepie, justo distal a la articulación metatarsofalángica del primer dedo, en la eminencia tenar del hallux. Solicita flexión del metatarsofalángico del primer dedo contra resistencia; el punto motor se localiza donde la contracción sea palpable con mínima estimulación.",
  "Flexor hallucis longus": "Con el paciente en decúbito supino y el tobillo en posición neutra, palpa en la región posterior-lateral de la pierna, aproximadamente 8–10 cm proximal al maléolo medial, justo lateral al tendón tibial posterior. Solicita flexión del dedo gordo contra resistencia; el punto motor se halla donde la contracción sea más evidente con la menor corriente.",
  "Flexor pollicis longus": "Paciente sentado con antebrazo apoyado y supinado. Palpa en la cara volar del antebrazo distal, a unos 6–7 cm proximal a la muñeca, justo medial al tendón del flexor digitorum profundus. Solicita flexión de la falange distal del pulgar contra resistencia; el punto motor se encuentra donde la contracción se genere con menor voltaje.",
  "Gastrocnemio (cabeza lateral)": "Con el paciente en decúbito prono y rodilla en ligera flexión (20–30°), palpa la región posterolateral de la pantorrilla, aproximadamente 5–6 cm distal a la línea de pliegue poplíteo y lateral al tendón de Aquiles. Solicita flexión plantar contra resistencia; el punto motor está donde aparezca la contracción con la menor estimulación.",
  "Gastrocnemio (cabeza medial)": "Con el paciente en decúbito prono y rodilla en ligera flexión, palpa la región posteromedial de la pantorrilla, aproximadamente 5–6 cm distal a la línea poplítea y medial al tendón de Aquiles. Solicita flexión plantar contra resistencia; el punto motor se localizará donde la contracción sea más intensa con bajo voltaje.",
  "Glúteo medio": "Paciente en decúbito lateral sobre el lado contralateral, con la cadera en ligera abducción. Palpa a nivel de la línea vertical que desciende desde la espina ilíaca anterosuperior, aproximadamente 6–8 cm inferior a la cresta iliaca, en la cara lateral del trocánter mayor. Solicita abducción de cadera contra resistencia; el punto motor se ubica donde se observe contracción con el menor voltaje.",
  "Gracilis": "Con el paciente en decúbito supino y la cadera en abducción y ligera rotación externa, palpa en la cara medial del muslo proximal, aproximadamente 8–10 cm distal a la sínfisis púbica, justo posterior al sartorio. Solicita aducción de cadera contra resistencia; el punto motor es donde la contracción se genere con mínima estimulación.",
  "Ilíaco": "Paciente en decúbito supino con rodilla y cadera relajadas. Palpa profundamente en la región inguinal, entre la cresta ilíaca y la espina ilíaca anterosuperior, alimentando la contracción solicitando flexión de cadera (como si levantara la rodilla hacia el pecho). El punto motor se halla donde la contracción se palpe con la menor corriente al presionar profundamente en el punto medio de la fosa iliaca.",
  "Infraespinoso": "Con el paciente en decúbito prono y el hombro en ligera abducción (15–20°), palpa en la fosa infraespinosa de la escápula, aproximadamente 2–3 cm inferior al borde lateral de la espina de la escápula. Solicita rotación externa de hombro contra resistencia (manteniendo el codo pegado al tronco); el punto motor se localiza donde la contracción sea más fuerte con la menor estimulación.",
  "Pectineus": "Paciente en decúbito supino y cadera en ligera abducción. Palpa en la región proximal-medial del muslo, aproximadamente 5–6 cm distal a la sínfisis púbica y justo inferior al pecten del pubis. Solicita flexión y aducción de cadera contra resistencia; el punto motor está donde la contracción se observe con el umbral más bajo.",
  "Pectoral mayor": "Con el paciente en decúbito supino y brazo en ligera abducción (30°), palpa en la región del pectoral mayor, aproximadamente a nivel de la línea media clavicular, unos 4–5 cm distal al esternón. Solicita aducción y rotación interna de hombro contra resistencia; el punto motor se halla donde la contracción sea más marcada con mínima corriente.",
  "Pectoralis minor": "Paciente en decúbito supino con el brazo relajado a lo largo del tronco. Palpa en la región infraclavicular, aproximadamente 2–3 cm medial al coracoides, entre la segunda y tercera costilla. Solicita depresión y rotación anterior de la escápula contra resistencia; el punto motor está donde la contracción del pectoral menor sea evidente con baja estimulación.",
  "Peroneus brevis": "Con el paciente en decúbito supino y el tobillo en ligera eversión y dorsiflexión neutra, palpa en la región distal-lateral de la pierna, aproximadamente 6–7 cm proximal al maléolo lateral, justo posterior al peroné. Solicita eversión del pie contra resistencia; el punto motor se localiza donde la contracción sea más evidente con mínima corriente.",
  "Peroneus longus": "Con el tobillo en dorsiflexión neutra y ligera eversión, palpa en la región lateral de la pierna, aproximadamente 8–10 cm proximal al maléolo lateral, justo anterior al peroné distal. Solicita eversión y plantar flexión del pie contra resistencia; el punto motor se halla donde la contracción se ve más potente al aplicar el menor voltaje.",
  "Peroneus tertius": "Paciente en decúbito supino con tobillo en dorsiflexión neutra. Palpa en la región anterolateral distal de la pierna, a unos 6 cm proximal al maléolo lateral, a nivel del primer metatarsiano. Solicita dorsiflexión y eversión del pie contra resistencia; el punto motor se encuentra donde la contracción es más visible con la menor corriente.",
  "Popliteus": "Con el paciente en decúbito prono y rodilla flexionada 90°, palpa en la región poplítea, justo posterior al epicóndilo femoral lateral, entre la cabeza del gastrocnemio lateral y el bíceps femoral proximal. Solicita rotación interna de la tibia contra resistencia; el punto motor se localiza donde se observe contracción con mínimo voltaje.",
  "Pronator quadratus": "Paciente sentado con antebrazo en pronación sobre la mesa. Palpa profundamente en la región distal del antebrazo, justo proximal a la muñeca, entre el cúbito y el radio. Solicita pronación forzada del antebrazo contra resistencia; el punto motor se halla donde la contracción sea más evidente con la menor corriente.",
  "Pronator teres": "Con el codo en ligera flexión (90°) y antebrazo en supinación, palpa la cara anterior del antebrazo proximal, aproximadamente 5–6 cm distal al epicóndilo medial, en la unión entre la cabeza humeral y cubital. Solicita pronación del antebrazo contra resistencia; el punto motor es donde la contracción se genere con el umbral más bajo.",
  "Psoas mayor": "Paciente en decúbito supino con rodilla y cadera relajadas. Palpa profundamente en la región inguinal, entre la espina ilíaca anterosuperior y el ombligo, a nivel de la fosa iliaca. Solicita flexión de cadera contra resistencia (como levantar la rodilla hacia el pecho); el punto motor se halla donde se genere la contracción con mínima estimulación, aproximadamente 2–3 cm profundo y medial al punto medio de la fosa iliaca.",
  "Rectus femoris (cuádriceps anterior)": "Con el paciente en decúbito supino y la pierna relajada, palpa en el vientre muscular del recto femoral, aproximadamente 10–12 cm proximal al borde superior de la rótula, en la línea media anterior del muslo. Solicita extensión de rodilla contra resistencia; el punto motor se ubicará donde la contracción sea máxima con la menor corriente.",
  "Redondo mayor": "Paciente sentado con el brazo colgando en aducción y rotación interna leve. Palpa en la región posterior-lateral de la axila, aproximadamente 5–6 cm distal al ángulo inferior de la escápula, cerca de la inserción humeral. Solicita aducción y rotación interna de hombro contra resistencia; el punto motor se halla donde la contracción se produzca con bajo voltaje.",
  "Redondo menor": "Con el paciente en decúbito prono y el brazo colgando en aducción, palpa en la región posterior del hombro, aproximadamente 2–3 cm inferior al borde lateral de la espina de la escápula y lateral a la fosa infraespinosa. Solicita rotación externa de hombro contra resistencia; el punto motor se localiza donde la contracción sea más marcada con mínima estimulación.",
  "Romboides": "Paciente en decúbito prono con brazo en aducción pasiva. Palpa las fibras del romboides mayor en la región medial de la espalda, entre las apófisis espinosas T2–T5 y el borde medial de la escápula. Solicita retracción escapular contra resistencia (como juntar las escápulas); el punto motor se halla donde la contracción sea más evidente con el umbral más bajo.",
  "Semimembranosus": "Con el paciente en decúbito prono y rodilla en ligera flexión, palpa la región posterior-medial del muslo, aproximadamente 6–8 cm distal a la tuberosidad isquiática, justo medial al semitendinoso. Solicita flexión de rodilla contra resistencia; el punto motor se ubica donde la contracción sea más nítida con mínima corriente.",
  "Semitendinosus": "Paciente en decúbito prono con la rodilla en ligera flexión, palpa en la región posterior-medial del muslo, aproximadamente 5–7 cm distal a la tuberosidad isquiática, justo lateral al semimembranoso. Solicita flexión de rodilla contra resistencia; el punto motor se halla donde la contracción sea más potente con bajo voltaje.",
  "Serrato anterior": "Con el paciente en decúbito supino y el brazo en 90° de flexión de hombro, palpa en la región lateral del tórax, aproximadamente a la altura de la axila, en la cara lateral de las costillas superiores (costillas 2–5). Solicita protraer la escápula contra resistencia (como empujar la mano hacia adelante); el punto motor se encuentra donde la contracción sea más evidente con la menor corriente.",
  "Sóleo": "Con el paciente en decúbito prono y rodilla flexionada 90°, palpa la región posterior de la pierna, aproximadamente 8–10 cm proximal al tendón de Aquiles, en la línea media. Solicita flexión plantar del tobillo contra resistencia; el punto motor se halla donde la contracción sea más intensa con mínima estimulación...",
  "Subscapularis": "Paciente en decúbito prono con el brazo en abducción de 90° y codo flexionado 90°. Palpa la región anterior de la escápula, aproximadamente 2–3 cm lateral al ángulo inferior de la escápula, en la fosa subescapular. Solicita rotación interna de hombro contra resistencia (codo pegado al cuerpo); el punto motor se ubica donde la contracción sea más clara con el umbral eléctrico más bajo.",
  "Superficial flexor muscles": "Este término agrupa los músculos flexores superficiales del antebrazo (flexor carpi radialis, flexor carpi ulnaris, flexor digitorum superficialis). Para su estimulación colectiva, coloca el electrodo en el tercio proximal del antebrazo volar, aproximadamente 6–8 cm distal al epicóndilo medial, en la zona donde las fibras musculares superficiales son más prominentes. Solicita flexión de muñeca y dedos contra resistencia; el punto motor grupal se localiza donde la contracción global sea máxima con menor corriente.",
  "Supinador": "Con el paciente sentado, codo en flexión de 90° y antebrazo en pronación, palpa en la región proximal-lateral del antebrazo, aproximadamente 5–6 cm distal al epicóndilo lateral, justo anterior al ECRL. Solicita supinación contra resistencia; el punto motor se halla donde la contracción sea más notoria con mínima estimulación.",
  "Supraespinoso": "Paciente en decúbito prono con el brazo colgando y en ligera abducción. Palpa en la fosa supraespinosa de la escápula, a nivel del punto medio entre el acromion y el ángulo superior de la escápula. Solicita abducción inicial del hombro contra resistencia (primeros 15°); el punto motor se sitúa donde la contracción se aprecie con la menor corriente.",
  "Tibialis anterior": "Con el paciente en decúbito supino y tobillo en posición neutra, palpa en la cara anterior-lateral de la pierna, aproximadamente 7–8 cm proximal al maléolo medial, justo lateral a la tibia. Solicita dorsiflexión del tobillo contra resistencia; el punto motor se ubica donde la contracción sea más intensa con bajo voltaje.",
  "Tibialis posterior": "Paciente en decúbito supino con la rodilla flexionada 30° y tobillo en ligera eversión. Palpa en la cara posterior-medial de la pierna, aproximadamente 8–10 cm proximal al maléolo medial, justo posterior a la tibia. Solicita inversión y flexión plantar del pie contra resistencia; el punto motor se localiza donde la contracción sea más clara con el umbral más bajo.",
  "Trapecio": "Con el paciente sentado o de pie, coloca el brazo en posición neutra. Para el trapecio superior, palpa la región cervical posterior, aproximadamente 2–3 cm lateral al ángulo superior de la escápula, en la unión entre el cuello y el hombro. Solicita elevación de hombros (encogimiento) contra resistencia; el punto motor se halla donde la contracción sea más fuerte con mínima corriente. Para el trapecio medio, palpa a nivel de T3–T4, 3–4 cm lateral a la línea media; solicita retracción escapular. Para el trapecio inferior, palpa a nivel de T8–T9, 4–5 cm lateral a la línea media; solicita depresión y rotación de escápula.",
  "Triceps brachii": "Con el paciente en decúbito prono y el brazo en ligera abducción, palpa en la región posterior del brazo, aproximadamente 6–8 cm proximal al olecranon, sobre la línea media posterior. Solicita extensión de codo contra resistencia; el punto motor se ubica donde la contracción sea más evidente con el menor voltaje.",
  "Vastus lateralis, intermedius y medialis": "Esta entrada agrupa los tres vastos del cuádriceps. El punto motor más accesible para estimulación conjunta se encuentra aproximadamente 10–12 cm proximal a la rótula sobre la cara anterior-lateral del muslo (para vasto lateral) y 8–10 cm proximal a la rótula sobre la cara medial (para vasto medial). Para el vasto intermedio (profundo), la estimulación superficial se logra mejor colocando el electrodo en la región media del muslo, justo por encima del vasto lateral. Solicita extensión de rodilla contra resistencia; los puntos motores se ubican donde cada vasto genere la contracción más potente con la menor corriente."
};
