import { useCallback, useMemo, useState } from 'react';
import type { MuscleSelection } from './useCalculatorState';
import {
  clampToBBox,
  convertOnaToBrand,
  detectRiskAt,
  FACIAL_MUSCLE_BY_ID,
  FACIAL_MUSCLES,
  getVolumeMl,
  mirrorSide,
  mirrorX,
  muscleHasLateralPoints,
  RISK_MESSAGES,
  type DefaultPointTemplate,
  type PointDepth,
  type PointSide,
  type RiskType,
  type SideMode,
  type ToxinBrand,
} from '../constants/facialAestheticMap';

export interface InjectionPoint {
  id: string;
  muscleId: string;
  muscleKey: string;
  x: number;
  y: number;
  doseOna: number;
  depth: PointDepth;
  side: PointSide;
  risk: RiskType | null;
  /** When true, this point was auto-generated by mirror sync */
  mirrored?: boolean;
}

export interface MuscleSummary {
  muscleId: string;
  muscleKey: string;
  name: string;
  totalOna: number;
  totalBrand: number;
  pointCount: number;
  maxDoseAesthetic: number;
  overDose: boolean;
  risks: RiskType[];
  sides: PointSide[];
}

export interface FacialPlanExport {
  brand: ToxinBrand;
  dilution: string;
  pathologyId: string;
  muscles: MuscleSelection[];
}

let pointIdCounter = 0;
function nextPointId(muscleId: string): string {
  pointIdCounter += 1;
  return `${muscleId}-${Date.now()}-${pointIdCounter}`;
}

function buildPoint(
  muscleId: string,
  template: DefaultPointTemplate,
  overrides?: Partial<Pick<InjectionPoint, 'x' | 'y' | 'doseOna' | 'depth' | 'side' | 'mirrored'>>
): InjectionPoint {
  const muscle = FACIAL_MUSCLE_BY_ID[muscleId];
  const x = overrides?.x ?? template.x;
  const y = overrides?.y ?? template.y;
  return {
    id: nextPointId(muscleId),
    muscleId,
    muscleKey: muscle.muscleKey,
    x,
    y,
    doseOna: overrides?.doseOna ?? template.doseOna,
    depth: overrides?.depth ?? template.depth,
    side: overrides?.side ?? template.side,
    risk: detectRiskAt(x, y),
    mirrored: overrides?.mirrored,
  };
}

/** ¿Existe al menos un punto de este músculo en este lado? */
function hasMuscleSide(
  points: InjectionPoint[],
  muscleId: string,
  side: PointSide
): boolean {
  return points.some((p) => p.muscleId === muscleId && p.side === side);
}

export interface UseFacialPlanOptions {
  initialBrand?: ToxinBrand;
  initialDilution?: string;
  /** true = bilateral (ambos), false = empieza en unilateral izq */
  mirrorModeDefault?: boolean;
  pathologyId?: string;
}

export function useFacialPlan(options: UseFacialPlanOptions = {}) {
  const [brand, setBrand] = useState<ToxinBrand>(options.initialBrand ?? 'Botox');
  const [dilution, setDilution] = useState(options.initialDilution ?? '2.5');
  const [sideMode, setSideMode] = useState<SideMode>(
    options.mirrorModeDefault === false ? 'izq' : 'ambos'
  );
  /** Al editar (mover/dosis), sincronizar el punto contralateral si existe */
  const [mirrorSync, setMirrorSync] = useState(options.mirrorModeDefault ?? true);
  const [points, setPoints] = useState<InjectionPoint[]>([]);
  const [activeMuscleIds, setActiveMuscleIds] = useState<Set<string>>(new Set());
  const [selectedPointId, setSelectedPointId] = useState<string | null>(null);
  const [showDangerZones, setShowDangerZones] = useState(true);
  const [layerVisibility, setLayerVisibility] = useState({
    skin: true,
    muscles: true,
    points: true,
    anatomy: true,
  });

  /** Compat: mirrorMode = selección bilateral */
  const mirrorMode = sideMode === 'ambos';
  const setMirrorMode = useCallback((on: boolean) => {
    setSideMode(on ? 'ambos' : 'izq');
    // Sync es independiente: no lo forzar aquí
  }, []);

  /**
   * Activa/desactiva puntos de un músculo según el modo lateral.
   * Criterio por presencia de lado (no por distancia a plantilla).
   * - ambos: toggle todo el músculo
   * - izq/der: toggle solo ese lado; conserva el contralateral y el centro
   */
  const toggleMuscle = useCallback(
    (muscleId: string, overrideSide?: SideMode) => {
      const muscle = FACIAL_MUSCLE_BY_ID[muscleId];
      if (!muscle) return;

      const mode = overrideSide ?? sideMode;

      // Músculos solo de línea media (prócer, mentoniano…)
      if (!muscleHasLateralPoints(muscle)) {
        setPoints((prev) => {
          const exists = prev.some((p) => p.muscleId === muscleId);
          if (exists) {
            const next = prev.filter((p) => p.muscleId !== muscleId);
            setActiveMuscleIds(new Set(next.map((p) => p.muscleId)));
            return next;
          }
          const added = muscle.defaultPoints.map((tpl) => buildPoint(muscleId, tpl));
          setActiveMuscleIds((ids) => new Set(ids).add(muscleId));
          return [...prev, ...added];
        });
        return;
      }

      setPoints((prev) => {
        const shouldRemove =
          mode === 'ambos'
            ? prev.some((p) => p.muscleId === muscleId)
            : hasMuscleSide(prev, muscleId, mode);

        if (shouldRemove) {
          const next = prev.filter((p) => {
            if (p.muscleId !== muscleId) return true;
            if (mode === 'ambos') return false;
            // Quitar solo el lado pedido; conservar contralateral y centro
            return p.side !== mode;
          });
          setActiveMuscleIds(new Set(next.map((p) => p.muscleId)));
          return next;
        }

        // Agregar plantillas del modo (sin centro en unilateral)
        const templates =
          mode === 'ambos'
            ? muscle.defaultPoints
            : muscle.defaultPoints.filter((t) => t.side === mode);

        const toAdd = templates
          .filter((tpl) => !hasMuscleSide(prev, muscleId, tpl.side))
          .map((tpl) => buildPoint(muscleId, tpl));

        if (toAdd.length === 0) return prev;

        setActiveMuscleIds((ids) => new Set(ids).add(muscleId));
        return [...prev, ...toAdd];
      });
    },
    [sideMode]
  );

  /** Quita un lado concreto de un músculo (o todo el músculo si side === 'ambos') */
  const removeMuscleSide = useCallback((muscleId: string, side: PointSide | 'ambos') => {
    setPoints((prev) => {
      const removedIds = new Set(
        prev
          .filter((p) => {
            if (p.muscleId !== muscleId) return false;
            if (side === 'ambos') return true;
            return p.side === side;
          })
          .map((p) => p.id)
      );
      const next = prev.filter((p) => !removedIds.has(p.id));
      setActiveMuscleIds(new Set(next.map((p) => p.muscleId)));
      setSelectedPointId((id) => (id && removedIds.has(id) ? null : id));
      return next;
    });
  }, []);

  /** Vacía todos los puntos de un lado en todo el plan */
  const clearLaterality = useCallback((side: 'izq' | 'der') => {
    setPoints((prev) => {
      const next = prev.filter((p) => p.side !== side);
      setActiveMuscleIds(new Set(next.map((p) => p.muscleId)));
      return next;
    });
    setSelectedPointId(null);
  }, []);

  const movePoint = useCallback(
    (pointId: string, x: number, y: number) => {
      setPoints((prev) => {
        const idx = prev.findIndex((p) => p.id === pointId);
        if (idx < 0) return prev;
        const point = prev[idx];
        const muscle = FACIAL_MUSCLE_BY_ID[point.muscleId];
        const clamped = clampToBBox(x, y, muscle.bbox);
        const updated: InjectionPoint = {
          ...point,
          x: clamped.x,
          y: clamped.y,
          risk: detectRiskAt(clamped.x, clamped.y),
          mirrored: false,
        };
        let next = [...prev];
        next[idx] = updated;

        if (mirrorSync && point.side !== 'centro') {
          const pairIdx = next.findIndex(
            (p) =>
              p.muscleId === point.muscleId &&
              p.id !== pointId &&
              p.side === mirrorSide(point.side)
          );
          if (pairIdx >= 0) {
            const mx = mirrorX(clamped.x);
            const mClamped = clampToBBox(mx, clamped.y, muscle.bbox);
            next[pairIdx] = {
              ...next[pairIdx],
              x: mClamped.x,
              y: mClamped.y,
              doseOna: updated.doseOna,
              depth: updated.depth,
              risk: detectRiskAt(mClamped.x, mClamped.y),
              mirrored: true,
            };
          }
        }
        return next;
      });
    },
    [mirrorSync]
  );

  const updatePointDose = useCallback(
    (pointId: string, delta: number) => {
      setPoints((prev) => {
        const idx = prev.findIndex((p) => p.id === pointId);
        if (idx < 0) return prev;
        const point = prev[idx];
        const newDose = Math.max(0.5, Math.round((point.doseOna + delta) * 2) / 2);
        let next = prev.map((p) => (p.id === pointId ? { ...p, doseOna: newDose } : p));

        if (mirrorSync && point.side !== 'centro') {
          next = next.map((p) =>
            p.muscleId === point.muscleId &&
            p.side === mirrorSide(point.side) &&
            p.id !== pointId
              ? { ...p, doseOna: newDose }
              : p
          );
        }
        return next;
      });
    },
    [mirrorSync]
  );

  const setPointDepth = useCallback(
    (pointId: string, depth: PointDepth) => {
      setPoints((prev) => {
        const point = prev.find((p) => p.id === pointId);
        if (!point) return prev;
        let next = prev.map((p) => (p.id === pointId ? { ...p, depth } : p));
        if (mirrorSync && point.side !== 'centro') {
          next = next.map((p) =>
            p.muscleId === point.muscleId &&
            p.side === mirrorSide(point.side) &&
            p.id !== pointId
              ? { ...p, depth }
              : p
          );
        }
        return next;
      });
    },
    [mirrorSync]
  );

  const removePoint = useCallback((pointId: string) => {
    setPoints((prev) => {
      const removed = prev.find((p) => p.id === pointId);
      const next = prev.filter((p) => p.id !== pointId);
      if (removed) {
        const still = next.some((p) => p.muscleId === removed.muscleId);
        if (!still) {
          setActiveMuscleIds((ids) => {
            const n = new Set(ids);
            n.delete(removed.muscleId);
            return n;
          });
        }
      }
      return next;
    });
    setSelectedPointId((id) => (id === pointId ? null : id));
  }, []);

  const clearPlan = useCallback(() => {
    setPoints([]);
    setActiveMuscleIds(new Set());
    setSelectedPointId(null);
  }, []);

  const loadPreset = useCallback((muscleIds: string[]) => {
    const newActive = new Set<string>();
    const newPoints: InjectionPoint[] = [];
    for (const id of muscleIds) {
      const muscle = FACIAL_MUSCLE_BY_ID[id];
      if (!muscle) continue;
      newActive.add(id);
      // Presets siempre bilaterales con las plantillas tal cual (sin duplicar espejo)
      for (const tpl of muscle.defaultPoints) {
        newPoints.push(buildPoint(id, tpl));
      }
    }
    setActiveMuscleIds(newActive);
    setPoints(newPoints);
    setSelectedPointId(null);
    setSideMode('ambos');
    setMirrorSync(true);
  }, []);

  const muscleSummaries = useMemo((): MuscleSummary[] => {
    const map = new Map<string, MuscleSummary>();
    for (const p of points) {
      const muscle = FACIAL_MUSCLE_BY_ID[p.muscleId];
      if (!muscle) continue;
      const existing = map.get(p.muscleId);
      if (existing) {
        existing.totalOna += p.doseOna;
        existing.pointCount += 1;
        if (p.risk && !existing.risks.includes(p.risk)) existing.risks.push(p.risk);
        if (!existing.sides.includes(p.side)) existing.sides.push(p.side);
      } else {
        map.set(p.muscleId, {
          muscleId: p.muscleId,
          muscleKey: muscle.muscleKey,
          name: muscle.name,
          totalOna: p.doseOna,
          totalBrand: 0,
          pointCount: 1,
          maxDoseAesthetic: muscle.maxDoseAesthetic,
          overDose: false,
          risks: p.risk ? [p.risk] : [],
          sides: [p.side],
        });
      }
    }
    return Array.from(map.values()).map((s) => {
      const totalBrand = convertOnaToBrand(s.totalOna, brand);
      return {
        ...s,
        totalBrand,
        overDose: s.totalOna > s.maxDoseAesthetic,
      };
    });
  }, [points, brand]);

  const totalOna = useMemo(() => points.reduce((sum, p) => sum + p.doseOna, 0), [points]);
  const totalBrandUnits = useMemo(() => convertOnaToBrand(totalOna, brand), [totalOna, brand]);
  const totalVolumeMl = useMemo(
    () => getVolumeMl(totalBrandUnits, brand, parseFloat(dilution) || 0),
    [totalBrandUnits, brand, dilution]
  );

  const activeRisks = useMemo(() => {
    const risks = new Set<RiskType>();
    points.forEach((p) => {
      if (p.risk) risks.add(p.risk);
    });
    return Array.from(risks).map((r) => RISK_MESSAGES[r]);
  }, [points]);

  const overDoseMuscles = useMemo(
    () => muscleSummaries.filter((s) => s.overDose).map((s) => s.name),
    [muscleSummaries]
  );

  const unitsBySide = useMemo(() => {
    let izq = 0;
    let der = 0;
    let centro = 0;
    for (const p of points) {
      const u = convertOnaToBrand(p.doseOna, brand);
      if (p.side === 'izq') izq += u;
      else if (p.side === 'der') der += u;
      else centro += u;
    }
    return { izq, der, centro };
  }, [points, brand]);

  const getMuscleActiveSides = useCallback(
    (muscleId: string): PointSide[] => {
      const sides = new Set<PointSide>();
      points.forEach((p) => {
        if (p.muscleId === muscleId) sides.add(p.side);
      });
      return Array.from(sides);
    },
    [points]
  );

  const exportPlan = useCallback((): FacialPlanExport => {
    type SideKey = 'Izquierdo' | 'Derecho' | 'Ambos';
    const grouped = new Map<string, { side: SideKey; doseOna: number }>();

    for (const p of points) {
      let side: SideKey;
      if (p.side === 'centro') side = 'Ambos';
      else if (p.side === 'izq') side = 'Izquierdo';
      else side = 'Derecho';

      const key = `${p.muscleKey}::${side}`;
      const existing = grouped.get(key);
      if (existing) existing.doseOna += p.doseOna;
      else grouped.set(key, { side, doseOna: p.doseOna });
    }

    const muscles: MuscleSelection[] = [];
    grouped.forEach((val, key) => {
      const muscleKey = key.split('::')[0];
      const customDose = convertOnaToBrand(val.doseOna, brand);
      muscles.push({
        id: `${muscleKey}-${val.side}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        name: muscleKey,
        side: val.side,
        doseOption: 'max',
        customDose,
      });
    });

    return {
      brand,
      dilution,
      pathologyId: options.pathologyId ?? 'estetica-facial',
      muscles,
    };
  }, [points, brand, dilution, options.pathologyId]);

  return {
    brand,
    setBrand,
    dilution,
    setDilution,
    sideMode,
    setSideMode,
    mirrorSync,
    setMirrorSync,
    mirrorMode,
    setMirrorMode,
    points,
    activeMuscleIds,
    selectedPointId,
    setSelectedPointId,
    showDangerZones,
    setShowDangerZones,
    layerVisibility,
    setLayerVisibility,
    toggleMuscle,
    removeMuscleSide,
    clearLaterality,
    movePoint,
    updatePointDose,
    setPointDepth,
    removePoint,
    clearPlan,
    loadPreset,
    getMuscleActiveSides,
    unitsBySide,
    muscleSummaries,
    totalOna,
    totalBrandUnits,
    totalVolumeMl,
    activeRisks,
    overDoseMuscles,
    exportPlan,
    musclesCatalog: FACIAL_MUSCLES,
  };
}

export type FacialPlanController = ReturnType<typeof useFacialPlan>;
